### ISSUE TITLE
Updating gallery

### ISSUE THREAD

**Issue by Fireballion** [purplecandy/ural#3]
Hi @purplecandy , when I take a new screenshot, it takes ages to appear on the home gallery of the app. I've implemented a continuous refresh function but that doesn't seem to help. How do I make this instantaneous?

**Comment by purplecandy** [comment]
It will happen that way because of the current all updates happen in the background and the background task runs periodically every 2 hours.  You can update that to a minimum of 15 minutes in the 
`lib/blocs/screen_bloc.dart` in the `startBackGroundJob()`

If you want to manually refresh at any given point you will have to just call `uploadImagesInBackground()` which is in `lib/background_tasks.dart` once it has completed it has completed you call the `listAllScreens()` from the screen_bloc

**Comment by Fireballion** [comment]
Thanks @purplecandy ! So can i not make it instant? If i loop the manual refresh like so in home.dart will that not do it? Also why is the minimum 15 minutes? Thanks again

**Comment by purplecandy** [comment]
The 15 minutes interval limitation is from the operating system because it's periodic task.

You can do it instantly
> If you want to manually refresh at any given point you will have to just call uploadImagesInBackground() which is in lib/background_tasks.dart once it has completed it has completed you call the listAllScreens() from the screen_bloc

**Comment by Fireballion** [comment]
Great @purplecandy ! I am trying this but it also produces duplicate images.

**Comment by Fireballion** [comment]
Is there any way to have screenshots taken instantly go to the home gallery without making duplicates in the gallery @purplecandy ?
